// packages/example-vue3/src/components/Accounts.vue
<script setup lang="ts">
import {Web3VueHooks} from "@web3-vue-org/core";
import type {Ref} from 'vue'
import {computed, ref, watchEffect} from "vue";
import type { BigNumber } from '@ethersproject/bignumber'
import { formatEther } from '@ethersproject/units'

interface Props {
  ENSNames: Web3VueHooks['ENSNames']['value']
  provider?: Web3VueHooks['provider']['value']
  accounts?: string[]
}

const props = defineProps<Props>()
const provider = computed(() => props.provider)
const accounts = computed(() => props.accounts)
const balances: Ref<BigNumber[] | undefined> = ref(undefined)

watchEffect(onCleanup => {
  if(provider.value && accounts.value?.length) {
    let stale = false
    void Promise.all(accounts.value!.map((account) => provider.value!.getBalance(account))).then((values) => {
      if (stale) return
      balances.value =  values
    })

    onCleanup(() => {
      stale = true
balances.value = undefined
    })
  }
})
</script>

<template>
  <div v-if="accounts">
    Accounts:
    <b>
      <template v-if="accounts.length === 0">None</template>
      <template v-else>
        <ul v-for="(account, i) in accounts" :key="account">
          {{ENSNames?.[i] ?? account}}
          {{balances?.[i] ? ` (Ξ${formatEther(balances[i])})` : null}}
        </ul>
      </template>
    </b>
  </div>
</template>

// example-next/components/Accounts.tsx
import type { BigNumber } from '@ethersproject/bignumber'
import { formatEther } from '@ethersproject/units'
import type { Web3VueHooks } from '@web3-vue-org/core'
import { useEffect, useState } from 'react'

function useBalances(
  provider?: ReturnType<Web3VueHooks['useProvider']>,
  accounts?: string[]
): BigNumber[] | undefined {
  const [balances, setBalances] = useState<BigNumber[] | undefined>()

  useEffect(() => {
    if (provider && accounts?.length) {
      let stale = false

      void Promise.all(accounts.map((account) => provider.getBalance(account))).then((balances) => {
        if (stale) return
        setBalances(balances)
      })

      return () => {
        stale = true
        setBalances(undefined)
      }
    }
  }, [provider, accounts])

  return balances
}

export function Accounts({
  accounts,
  provider,
  ENSNames,
}: {
  accounts: ReturnType<Web3VueHooks['useAccounts']>
  provider: ReturnType<Web3VueHooks['useProvider']>
  ENSNames: ReturnType<Web3VueHooks['useENSNames']>
}) {
  const balances = useBalances(provider, accounts)

  if (accounts === undefined) return null

  return (
    <div>
      Accounts:{' '}
      <b>
        {accounts.length === 0
          ? 'None'
          : accounts?.map((account, i) => (
              <ul key={account} style={{ margin: 0, overflow: 'hidden', textOverflow: 'ellipsis' }}>
                {ENSNames?.[i] ?? account}
                {balances?.[i] ? ` (Ξ${formatEther(balances[i])})` : null}
              </ul>
            ))}
      </b>
    </div>
  )
}
