// packages/example-vue3/src/components/Card.vue
<script setup lang="ts">
import {CoinbaseWallet} from "@web3-vue-org/coinbase-wallet";
import type {Web3VueHooks} from "@web3-vue-org/core";
import {MetaMask} from "@web3-vue-org/metamask";
import {Network} from "@web3-vue-org/network";
import {WalletConnect} from "@web3-vue-org/walletconnect";
import {computed} from "vue";
import {getName} from "@/utils";
import ChainId from "@/components/ChainId.vue";
import Accounts from "@/components/Accounts.vue";
import ConnectWithSelect from "@/components/ConnectWithSelect.vue";

interface Props {
  connector: MetaMask | WalletConnect | CoinbaseWallet | Network
  chainId: Web3VueHooks['chainId']['value']
  isActivating: Web3VueHooks['isActivating']['value']
  isActive: Web3VueHooks['isActive']['value']
  error: Error | undefined
  setError: (error: Error | undefined) => void
  ENSNames: Web3VueHooks['ENSNames']['value']
  provider?: Web3VueHooks['provider']['value']
  accounts?: string[]
}

const props = defineProps<Props>()
const connector = computed(() =>props.connector)
const error = computed(() => props.error)
const isActivating = computed(() => props.isActivating)
const isActive = computed(() => props.isActive)
const chainId = computed(() => props.chainId)
const accounts = computed(() => props.accounts)
</script>

<template>
  <div class="card">
    <b>{{getName(connector)}}</b>
    <div style="margin-bottom: 1rem">
      <div v-if="error">🔴 {{error.name ?? 'Error'}} {{error.message ? `: ${error.message}` : ''}}</div>
      <div v-else-if="isActivating">🟡 Connecting</div>
      <div v-else-if="isActive">🟢 Connected</div>
      <div v-else>⚪️ Disconnected</div>
  </div>
    <ChainId v-if="chainId" :chain-id="chainId"></ChainId>
    <div style="margin-bottom: 1rem">
  <Accounts :accounts="accounts" :provider="provider" :ENSNames="ENSNames" />
      <ConnectWithSelect :chain-id="chainId" :connector="connector" :error="error" :is-activating="isActivating" :is-active="isActive" :set-error="setError"></ConnectWithSelect>
  </div>
  </div>
</template>

<style scoped>
.card {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  width: 20rem;
  padding: 1rem;
  margin: 1rem;
  overflow: auto;
  border: 1px solid;
  border-radius: 1rem;
}
</style>

// example-next/components/Card.tsx
import { CoinbaseWallet } from '@web3-vue-org/coinbase-wallet'
import { Web3ReactHooks } from '@web3-vue-org/core'
import { GnosisSafe } from '@web3-vue-org/gnosis-safe'
import { MetaMask } from '@web3-vue-org/metamask'
import { Network } from '@web3-vue-org/network'
import { WalletConnect } from '@web3-vue-org/walletconnect'
import { getName } from '../utils'
import { Accounts } from './Accounts'
import { Chain } from './Chain'
import { ConnectWithSelect } from './ConnectWithSelect'
import { Status } from './Status'

interface Props {
  connector: MetaMask | WalletConnect | CoinbaseWallet | Network | GnosisSafe
  chainId: ReturnType<Web3ReactHooks['useChainId']>
  isActivating: ReturnType<Web3ReactHooks['useIsActivating']>
  isActive: ReturnType<Web3ReactHooks['useIsActive']>
  error: Error | undefined
  setError: (error: Error | undefined) => void
  ENSNames: ReturnType<Web3ReactHooks['useENSNames']>
  provider?: ReturnType<Web3ReactHooks['useProvider']>
  accounts?: string[]
}

export function Card({
  connector,
  chainId,
  isActivating,
  isActive,
  error,
  setError,
  ENSNames,
  accounts,
  provider,
}: Props) {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        width: '20rem',
        padding: '1rem',
        margin: '1rem',
        overflow: 'auto',
        border: '1px solid',
        borderRadius: '1rem',
      }}
    >
      <b>{getName(connector)}</b>
      <div style={{ marginBottom: '1rem' }}>
        <Status isActivating={isActivating} isActive={isActive} error={error} />
      </div>
      <Chain chainId={chainId} />
      <div style={{ marginBottom: '1rem' }}>
        <Accounts accounts={accounts} provider={provider} ENSNames={ENSNames} />
      </div>
      <ConnectWithSelect
        connector={connector}
        chainId={chainId}
        isActivating={isActivating}
        isActive={isActive}
        error={error}
        setError={setError}
      />
    </div>
  )
}
