// example-next/components/ConnectWithSelect.tsx
import type { CoinbaseWallet } from '@web3-vue-org/coinbase-wallet'
import type { Web3ReactHooks } from '@web3-vue-org/core'
import { GnosisSafe } from '@web3-vue-org/gnosis-safe'
import type { MetaMask } from '@web3-vue-org/metamask'
import { Network } from '@web3-vue-org/network'
import { WalletConnect } from '@web3-vue-org/walletconnect'
import { useCallback, useState } from 'react'
import { CHAINS, getAddChainParameters, URLS } from '../chains'

function ChainSelect({
  chainId,
  switchChain,
  displayDefault,
  chainIds,
}: {
  chainId: number
  switchChain: (chainId: number) => void | undefined
  displayDefault: boolean
  chainIds: number[]
}) {
  return (
    <select
      value={chainId}
      onChange={(event) => {
        switchChain?.(Number(event.target.value))
      }}
      disabled={switchChain === undefined}
    >
      {displayDefault ? <option value={-1}>Default Chain</option> : null}
      {chainIds.map((chainId) => (
        <option key={chainId} value={chainId}>
          {CHAINS[chainId]?.name ?? chainId}
        </option>
      ))}
    </select>
  )
}

export function ConnectWithSelect({
  connector,
  chainId,
  isActivating,
  isActive,
  error,
  setError,
}: {
  connector: MetaMask | WalletConnect | CoinbaseWallet | Network | GnosisSafe
  chainId: ReturnType<Web3ReactHooks['useChainId']>
  isActivating: ReturnType<Web3ReactHooks['useIsActivating']>
  isActive: ReturnType<Web3ReactHooks['useIsActive']>
  error: Error | undefined
  setError: (error: Error | undefined) => void
}) {
  const isNetwork = connector instanceof Network
  const displayDefault = !isNetwork
  const chainIds = (isNetwork ? Object.keys(URLS) : Object.keys(CHAINS)).map((chainId) => Number(chainId))

  const [desiredChainId, setDesiredChainId] = useState<number>(isNetwork ? 1 : -1)

  const switchChain = useCallback(
    (desiredChainId: number) => {
      setDesiredChainId(desiredChainId)
      // if we're already connected to the desired chain, return
      if (desiredChainId === chainId) {
        setError(undefined)
        return
      }

      // if they want to connect to the default chain and we're already connected, return
      if (desiredChainId === -1 && chainId !== undefined) {
        setError(undefined)
        return
      }

      if (connector instanceof WalletConnect || connector instanceof Network) {
        connector
          .activate(desiredChainId === -1 ? undefined : desiredChainId)
          .then(() => setError(undefined))
          .catch(setError)
      } else {
        connector
          .activate(desiredChainId === -1 ? undefined : getAddChainParameters(desiredChainId))
          .then(() => setError(undefined))
          .catch(setError)
      }
    },
    [connector, chainId, setError]
  )

  const onClick = useCallback((): void => {
    setError(undefined)
    if (connector instanceof GnosisSafe) {
      connector
        .activate()
        .then(() => setError(undefined))
        .catch(setError)
    } else if (connector instanceof WalletConnect || connector instanceof Network) {
      connector
        .activate(desiredChainId === -1 ? undefined : desiredChainId)
        .then(() => setError(undefined))
        .catch(setError)
    } else {
      connector
        .activate(desiredChainId === -1 ? undefined : getAddChainParameters(desiredChainId))
        .then(() => setError(undefined))
        .catch(setError)
    }
  }, [connector, desiredChainId, setError])

  if (error) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column' }}>
        {!(connector instanceof GnosisSafe) && (
          <ChainSelect
            chainId={desiredChainId}
            switchChain={switchChain}
            displayDefault={displayDefault}
            chainIds={chainIds}
          />
        )}
        <div style={{ marginBottom: '1rem' }} />
        <button onClick={onClick}>Try Again?</button>
      </div>
    )
  } else if (isActive) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column' }}>
        {!(connector instanceof GnosisSafe) && (
          <ChainSelect
            chainId={desiredChainId === -1 ? -1 : chainId}
            switchChain={switchChain}
            displayDefault={displayDefault}
            chainIds={chainIds}
          />
        )}
        <div style={{ marginBottom: '1rem' }} />
        <button
          onClick={() => {
            if (connector?.deactivate) {
              void connector.deactivate()
            } else {
              void connector.resetState()
            }
          }}
        >
          Disconnect
        </button>
      </div>
    )
  } else {
    return (
      <div style={{ display: 'flex', flexDirection: 'column' }}>
        {!(connector instanceof GnosisSafe) && (
          <ChainSelect
            chainId={desiredChainId}
            switchChain={isActivating ? undefined : switchChain}
            displayDefault={displayDefault}
            chainIds={chainIds}
          />
        )}
        <div style={{ marginBottom: '1rem' }} />
        <button
          onClick={
            isActivating
              ? undefined
              : () =>
                  connector instanceof GnosisSafe
                    ? void connector
                        .activate()
                        .then(() => setError(undefined))
                        .catch(setError)
                    : connector instanceof WalletConnect || connector instanceof Network
                    ? connector
                        .activate(desiredChainId === -1 ? undefined : desiredChainId)
                        .then(() => setError(undefined))
                        .catch(setError)
                    : connector
                        .activate(desiredChainId === -1 ? undefined : getAddChainParameters(desiredChainId))
                        .then(() => setError(undefined))
                        .catch(setError)
          }
          disabled={isActivating}
        >
          Connect
        </button>
      </div>
    )
  }
}

// packages/example-vue3/src/components/ConnectWithSelect.vue
<script setup lang="ts">
import {CHAINS, getAddChainParameters} from "@/chains";
import {CoinbaseWallet} from "@web3-vue-org/coinbase-wallet";
import {Web3VueHooks} from "@web3-vue-org/core";
import {MetaMask} from "@web3-vue-org/metamask";
import {Network} from "@web3-vue-org/network";
import {WalletConnect} from "@web3-vue-org/walletconnect";
import {ref} from "vue";

interface Props {
  connector: MetaMask | WalletConnect | CoinbaseWallet | Network
  chainId: Web3VueHooks['chainId']['value']
  isActivating: Web3VueHooks['isActivating']['value']
  isActive: Web3VueHooks['isActive']['value']
  error: Error | undefined
  setError: (error: Error | undefined) => void
}

const props = defineProps<Props>()

const chainIds =  Object.keys(CHAINS).map((chainId) => Number(chainId))

const desiredChainId = ref(props.connector instanceof Network ? 1 : -1)

function onClick() {

}

function onDeactivate() {
  if (props.connector?.deactivate) {
  props.connector.deactivate()
  } else {
props.connector.resetState()
  }
}

function onConnect() {
  if (props.isActivating) {
    return
  }
  if (props.connector instanceof WalletConnect || props.connector instanceof Network) {
    props.connector
        .activate(desiredChainId.value === -1 ? undefined : desiredChainId.value)
        .then(() => props.setError(undefined))
        .catch(props.setError)
  } else {
    props.connector
        .activate(desiredChainId.value === -1 ? undefined : getAddChainParameters(desiredChainId.value))
        .then(() => props.setError(undefined))
        .catch(props.setError)
  }
}

function switchChain(id: number) {
  desiredChainId.value = id
  // if we're already connected to the desired chain, return
  if (id === props.chainId) {
    props.setError(undefined)
    return
  }

  // if they want to connect to the default chain and we're already connected, return
  if (id === -1 && props.chainId > 0) {
    props.setError(undefined)
    return
  }

  if (props.connector instanceof WalletConnect || props.connector instanceof Network) {
    props.connector
        .activate(id === -1 ? undefined : id)
        .then(() => props.setError(undefined))
        .catch(props.setError)
  } else {
    props.connector
        .activate(id === -1 ? undefined : getAddChainParameters(id))
        .then(() => props.setError(undefined))
        .catch(props.setError)
  }
}
</script>

<template>
  <div style="display: flex;flex-direction: column" >
    <select
        :value="chainId"
        @change="(event) => switchChain(Number(event.target.value))"
    >
    <option :value="-1">Default Chain</option>

    <option v-for="chainId in chainIds" :key="chainId" :value="chainId">
      {{CHAINS[chainId]?.name ?? chainId }}
    </option>
    </select>
    <div style="margin-bottom: 1rem"></div>
    <button v-if="error" @click="onClick">Try Again</button>
    <button v-else-if="isActive" @click="onDeactivate">Disconnect</button>
    <button v-else @click="onConnect">Connect</button>
  </div>
</template>
