// example-next/components/connectorCards/WalletConnectCard.tsx
import { URI_AVAILABLE } from '@web3-vue-org/walletconnect'
import { useEffect, useState } from 'react'
import { hooks, walletConnect } from '../../connectors/walletConnect'
import { Card } from '../Card'

const { useChainId, useAccounts, useIsActivating, useIsActive, useProvider, useENSNames } = hooks

export default function WalletConnectCard() {
  const chainId = useChainId()
  const accounts = useAccounts()
  const isActivating = useIsActivating()

  const isActive = useIsActive()

  const provider = useProvider()
  const ENSNames = useENSNames(provider)

  const [error, setError] = useState(undefined)

  // log URI when available
  useEffect(() => {
    walletConnect.events.on(URI_AVAILABLE, (uri: string) => {
      console.log(`uri: ${uri}`)
    })
  }, [])

  // attempt to connect eagerly on mount
  useEffect(() => {
    walletConnect.connectEagerly().catch(() => {
      console.debug('Failed to connect eagerly to walletconnect')
    })
  }, [])

  return (
    <Card
      connector={walletConnect}
      chainId={chainId}
      isActivating={isActivating}
      isActive={isActive}
      error={error}
      setError={setError}
      accounts={accounts}
      provider={provider}
      ENSNames={ENSNames}
    />
  )
}

// example-vue3/src/components/connectorCards/WalletConnectCard.vue
<script setup lang="ts">
import Card from "@/components/Card.vue";
import { hooks, walletConnect } from '@/connectors/walletConnect'
import { ref} from "vue";
import type {Ref} from 'vue'

const error: Ref<Error | undefined> = ref(undefined)

const chainId = hooks.chainId
const accounts = hooks.accounts
const isActivating = hooks.isActivating

const isActive = hooks.isActive

const provider = hooks.provider
const ENSNames = hooks.ENSNames

walletConnect.connectEagerly().catch(() => {
  console.debug('Failed to connect eagerly to wallet connect')
})

function setError(e: Error) {
  error.value = e
}
</script>

<template>
  <Card
      :connector="walletConnect"
      :chainId="chainId"
      :isActivating="isActivating"
      :isActive="isActive"
      :accounts="accounts"
      :provider="provider"
      :ENSNames="ENSNames"
      :error="error"
      :set-error="setError"
  />
</template>
